### ISSUE TITLE
Breakout sessions for Tools/NextSteps should begin at start of day

### ISSUE THREAD

**Issue by lightandluck** [DataRescueSFBay/DataRescueSFBay-Event#15]
Hi all, I participated in the UI session that happened after lunch on Saturday. IMO, it felt very hurried and a lot of time was spent just trying to communicate problems and objectives. There was a huge pool of talent and expertise available, but not enough time to fully utilize our collective resources. Humbly suggest these sessions break off immediately at the beginning of future events. Having an extra 2-3 hours would have been invaluable.

**Comment by ottumm** [comment]
I think that's a great idea. I personally learned a lot of lessons in general about starting quickly and maximizing participants' time while everyone's together, and this is a great note.
